[package]
name = "rust-warrior"
description = "Game for learning Rust, inspired by Ruby Warrior"
version = "0.8.2"
repository = "https://github.com/miller-time/rust-warrior"
documentation = "https://docs.rs/rust-warrior/"
readme = "README.md"
keywords = ["game", "learning", "rust", "specs"]
categories = ["games"]
license = "MIT"
authors = ["Russell Cousineau <miller.time.baby@gmail.com>"]
edition = "2018"

[badges.maintenance]
status = "actively-developed"

[dependencies]
base64 = "0.10"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"

[dependencies.specs]
version = "0.15"
features = ["specs-derive"]
