[package]
name = "rust-warrior"
version = "0.1.0"
authors = ["Russell Cousineau <miller.time.baby@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
