[package]
name = "rust-warrior"
description = "Game for learning Rust, inspired by Ruby Warrior"
version = "0.3.0"
repository = "https://gitlab.com/rcousineau/rust-warrior"
documentation = "https://docs.rs/rust-warrior/"
license = "MIT"
authors = ["Russell Cousineau <miller.time.baby@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.5.1"
base64 = "0.2.0"

[dependencies.specs]
version = "0.15.0"
features = ["specs-derive"]
